[project]
name = "awesome-fastapi"
version = "0.1.0"
description = "This project is for practicing fastapi"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
]

[tool.fastapi-cli]
app = "backend.main:app"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"